config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  get '/user/:id/edit', to: 'user#edit', as: :update_user
  patch '/user/:id/edit', to: 'user#update'

  get '/group', to: 'group#index'
  get '/group/new', to: 'group#new'
  post '/group/new', to: 'group#create'
  get '/group/:id/transactions', to: 'group#show', as: :single_group
  get '/group/:id/edit', to: 'group#edit', as: :update_group
  patch '/group/:id/edit', to: 'group#update'
  get '/group/:id/delete', to: 'group#destroy', as: :delete_group
  get '/transactions', to: 'entity#index'
  get '/transactions/new', to: 'entity#new'
  post '/transactions/new', to: 'entity#create'
  get '/transactions/:id/edit', to: 'entity#edit', as: :update_transaction
  patch '/transactions/:id/edit', to: 'entity#update'
  get '/transactions/:id/delete', to: 'entity#destroy', as: :delete_transaction

  # Defines the root path route ("/")
  root "splash#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      can :manage, :all
      can :manage, Entite, user_id: user.id
      can :manage, Group, user_id: user.id
      can :manage, User, user_id: user.id
    else
      can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entite.rb
class Entite < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :name, presence: true
  validates :amount, presence: true
  validates :group_id, presence: true
end

app/models/entity.rb
class Entite < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities, class_name: 'Entite', dependent: :delete_all
  has_one_attached :icon

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :groups, foreign_key: 'user_id'
  has_many :entities, class_name: 'Entite'

  validates :name, presence: true
  validates :password, presence: true, :on => :create

  has_one_attached :profile_pic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_pic, :name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:profile_pic, :name, :email])
  end

  def check_signed_in
    redirect_to transactions_path if signed_in?
  end
end

app/controllers/entity_controller.rb
class EntityController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = current_user.entities.includes(:group).order('created_at DESC')
  end

  def new
    @entity = Entite.new
    @groups = Group.all
  end

  def show
    @groups = Group.all
  end

  def create
    if session[:is_transaction_triggered_from_detail] && transaction_params_without_group_id[:name] && transaction_params_without_group_id[:amount]
      @new_transaction = current_user.entities.new(transaction_params_without_group_id)
      @new_transaction.group_id = session[:group_id]
      persist_data(@new_transaction)

    elsif transaction_params[:name] && transaction_params[:amount] && transaction_params[:group_id]
      @new_transaction = current_user.entities.new(transaction_params)
      persist_data(@new_transaction)
    else
      @groups = Group.all
      flash[:notice] = "Please fill in the entire form"
      render :new
    end
  end

  def edit
    @entity = Entite.find(params[:id])
    @groups = Group.all
  end

  def update
    @entity = Entite.find(params[:id])

    if @entity.update(transaction_params)
      flash[:notice] = "Transaction updated successfully"
      redirect_to single_group_path(@entity.group_id)
    else
      @groups = Group.all
      render :edit
    end
  end

  def destroy
    @entity = Entite.find(params[:id])

    # keep a copy of the deleted entity group
    @group_id = @entity.group_id
    @entity.destroy

    flash[:notice] = 'Transaction deleted'
    redirect_to single_group_path(@group_id)
  end

  private

  def transaction_params_without_group_id
    params.permit(:name, :amount)
  end

  def transaction_params
    params.permit(:name, :amount, :group_id)
  end

  def persist_data(instance_variable)
    if instance_variable.save
      flash[:notice] = "New transcation added successfully"
      redirect_to single_group_path(instance_variable.group_id)
    else
      @groups = Group.all
      render :new
    end
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, :clear_sessions

  def index
    @groups = current_user.groups.includes(:entities).order('created_at desc')
  end

  def show
    @group = Group.includes(:entities).find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    if group_params[:name] && group_params[:icon]
      @new_group = current_user.groups.new(group_params)
      if @new_group.save
        flash[:notice] = "New category created successfully"
        redirect_to group_path
      else
        render :new
      end
    else
      flash[:notice] = "Please enter a name and upload an icon to continue"
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      flash[:notice] = "Category updated successfully"
      redirect_to single_group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = 'Category deleted'
    redirect_to group_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def clear_sessions
    session[:is_transaction_triggered_from_detail] = nil
    session[:group_id] = nil
  end
end

app/controllers/registrations_controller.rb
# app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  before_action :check_signed_in

  def index; end

  def check_signed_in
    redirect_to group_path if signed_in?
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  load_and_authorize_resource
  def edit
    @user = current_user
    render "users/registrations/edit"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entity_helper.rb
module EntityHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/entity/edit.html.erb
<% session[:current_page] = "EDITING TRANSACTION" %>

<%= render partial: "partials/transactionForm",
  locals: { entity_model: @entity, entity_path: update_transaction_path, groups: @groups } %>

app/views/entity/index.html.erb
<% session[:current_page] = "TRANSACTIONS" %>

<%# pass all transactions to the show card %>
<%= render partial: "partials/showCard", locals: { view: "transaction", data: @transactions }  %>

<%# Add transaction button %>
<%= render partial: "partials/addTransactionButton", locals: { addSessionVariable: false, group_id: nil } %>

app/views/entity/new.html.erb
<% session[:current_page] = "CREATE A TRANSACTION" %>

<%= render partial: "partials/transactionForm",
  locals: { entity_model: @entity, entity_path: transactions_new_path, groups: @groups } %>

app/views/group/edit.html.erb
<% session[:current_page] = "EDITING CATEGORY" %>

<%= render partial: "partials/categoryForm",
  locals: { group_model: @group, group_path: update_group_path } %>

app/views/group/index.html.erb
<% session[:current_page] = "CATEGORY" %>

<%# pass all groups to the display show card %>
<%= render partial: "partials/showCard", locals: { view: "group", data: @groups } %>

<%# add new category button section %>
<%= render partial: "partials/addCategoryButton" %>

app/views/group/new.html.erb
<% session[:current_page] = "CREATE A CATEGORY" %>

<%= render partial: "partials/categoryForm",
  locals: { group_model: @group, group_path: group_new_path } %>

app/views/group/show.html.erb
<% session[:current_page] = "DETAILS" %>
<div class="pb-36">
  <div class="py-2 px-3">
    <div class="bg-white rounded h-auto p-2 space-x-3 shadow-m">

      <%# category section %>
      <%= render partial: "partials/categoryShowCard", locals: { group: @group } %>
      
      <%# list of transactions for a single group %>
      <%= render partial: "partials/listTransactions", locals: { group: @group } %>
    </div>
  </div>
</div>

<%# Add transaction button %>
<%= render partial: "partials/addTransactionButton", locals: { addSessionVariable: true, group_id: @group.id } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pense App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="bg-gray-200 h-screen">
      <%= render "partials/primary_navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_addCategoryButton.html.erb
<div class="bg-primary-green h-24 flex items-center justify-center p-4 fixed bottom-0 z-20 w-full">
  <%= link_to group_new_path do %>
    <div class="border border-white w-full h-16 text-white flex items-center justify-center rounded-md px-16">
      <p>ADD NEW CATEGORY</p>
    </div>
  <% end %>
</div>

app/views/partials/_addTransactionButton.html.erb
<div class="bg-primary-green h-24 flex items-center justify-center p-4 fixed bottom-0 z-20 w-full">
  <%= link_to transactions_new_path do %>
    <% if addSessionVariable %>
      <% session[:is_transaction_triggered_from_detail] = "/group/:id/transactions", session[:group_id] = group_id %>
    <% end %>

    <div class="border border-white w-full h-16 text-white flex items-center justify-center rounded-md px-16">
      <p>ADD TRANSACTION</p>
    </div>
  <% end %>
</div>

app/views/partials/_categoryForm.html.erb
<div class="bg-gray h-screen">
  <%= form_with model: group_model, url: group_path do |f| %>
    <%= render "users/shared/error_messages", resource: group_model %>

    <div class="mt-10 text-primary-gray">
      <%= f.text_field :name,
        autofocus: true,
        autocomplete: "name",
        placeholder: "Category Name",
        class: "appearance-none block w-full px-3 py-2 border border-gray-300 h-14 focus:outline-none focus:ring-primary-blue focus:border-primary-blue" %>

      <div class="appearance-none items-center space-x-6 w-full px-3 py-4 border border-gray-300 h-auto focus:outline-none focus:ring-primary-blue focus:border-primary-blue flex">
      <%# only show if the path is for editing %>
        <% if group_path != group_new_path %>
          <div class="h-16 w-16">
            <% if @group.icon.attached? %>
              <%= image_tag @group.icon, alt: "group-photo", id: "preview_profile_pic_tag", class: "rounded-full h-full w-full" %>
            <% end %>
          </div>
          <label for="profile_pic_tag">Update Icon</label>
        <% else %>
          <div class="h-14 w-14 rounded-full bg-gray-400">
            <%= image_tag "mg.png", id: "preview_profile_pic_tag", class: "rounded-full h-full w-full" %>
          </div>
          <label for="profile_pic_tag">Upload Icon</label>
        <% end %>
          
        <%= f.file_field :icon, id: "profile_pic_tag", class: "hidden" %>
        
        </div>
      </div>

      <div class="flex items-center justify-center mt-16">
        <% if group_path != group_new_path %>
          <%= f.submit "UPDATE", class: "actions cursor-pointer bg-primary-green p-4 w-48 rounded-md text-white font-semibold text-center" %>
        <% else %>
          <%= f.submit "SAVE", class: "actions cursor-pointer bg-primary-green p-4 w-48 rounded-md text-white font-semibold text-center" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_categoryShowCard.html.erb
<div class="flex mb-2">
  <div class="h-16 w-16">
    <% if group.icon.attached? %>
      <%= image_tag group.icon, alt: "group-photo" %>
    <% end %>
  </div>
  <div class="flex flex-col justify-between ml-5">
    <p class="text-gray-500 mb-2"><%= group.name %></p>
    <div class="flex space-x-8">
      <span class="bg-gray-100 p-2 rounded-full">
        <%= link_to update_group_path(group) do %>
          <%= image_tag "edit-file.svg", alt: "edit-icon", class: "h-6" %>
        <% end %>
      </span>
      <span class="bg-gray-100 p-2 rounded-full btn-open-cate-popup">
        <%= image_tag "trash-bin.svg", alt: "trash-icon", class: "h-6 cursor-pointer show-card-trash-bin" %>
      </span>
    </div>
  </div>
</div>

<%# popup modal %>
<div class="confirm-category-delete hidden">
<%= render partial: "partials/delete_confirm_popup",
  locals: { caller_delete_route: delete_group_path(
    @group), message: "Delete Category" } %>
</div>

app/views/partials/_listTransactions.html.erb
<% group.entities.order('created_at desc').each do |transaction| %>
  <div class="text-gray-500 text-sm mt-4 border-t">
    <div class="my-3 py-1">
      <div class="flex justify-between py-3">
        <p class="font-semibold pb-2">
          <%= transaction.name %>
        </p>
        <div class="flex space-x-6">
        <span class="bg-gray-100 p-2 rounded-full">
          <%= link_to update_transaction_path(transaction) do %>
            <%= image_tag "edit-file.svg", alt: "edit-icon", class: "h-5" %>
          <% end %>
        </span>
        <span class="bg-gray-100 p-2 rounded-full btn-open-trans-popup" id="<%= transaction.id %>">
          <%= image_tag "trash-bin.svg", alt: "trash-icon", class: "h-5" %>
        </span>
        </div>
      </div>
      <div class="flex justify-between">
        <p>
          <%= transaction.created_at.strftime("%e %b, %Y at %H:%M") %>
        </p>
        <p>$ <%= transaction.amount %></p>
      </div>
    </div>
  </div>
<% end %>

<div class="flex justify-between items-center py-2 border-t">
  <% if group.entities.exists? %>
    <p class="text-gray-500">TOTAL PAYMENT</p>
    <p class="font-semibold">$<%= group.entities.sum(:amount) %></p>
  <% else %>
    <p class="text-center font-semibold pb-2">No transactions available</p>
  <% end %>
</div>

<div class="confirm-transaction-delete hidden">
  <%= render partial: "partials/delete_confirm_popup",
    locals: { caller_delete_route:  nil, message: "Delete Transaction" } %>
</div>

app/views/partials/_notices.html.erb
<% if notice || alert %>
  <div class="">
    <div class="h-auto">
      <div class="my-5 text-center bg-blue-50 border border-blue-400 text-blue-800 p-2 rounded-md notice-card  mx-5">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/partials/_primary_navbar.html.erb
<% if user_signed_in? %>
  <div class="fixed top-0 z-20 w-full">
    <div class="bg-primary-blue h-auto py-5">
      <div class="flex items-center justify-between text-white px-4">
        <button>
          <% if request.path == group_path || request.path == transactions_path %>
            <%= image_tag "hamburger-menu.svg", alt: "group-photo", class: "h-5 hamburger-menu-icon" %>
          <% else %>
            <%= link_to "<-", root_path, class: 'text-lg font-bold' %>
          <% end %>
        </button>
        <p class="w-full text-center"><%= session[:current_page] %></p>
        <button class="cursor-pointer">
          <%= button_to destroy_user_session_path, method: :delete do %>
            <%= image_tag "exit-sign.svg", alt: "group-photo", class: "h-5" %>
          <% end %>
        </button>
      </div>
    </div>

    <%# show group card if on group page %>
    <% if request.path == group_path %>
      <div class="shadow-xl h-14 flex items-center justify-between px-4 bg-white">
        <p class="text-gray-500">Hello, <%= current_user.name%></p>
        <p class="text-gray-700 font-semibold"></p>
      </div>
    <% end %>

    <%# show gift card if on transaction page %>
    <% if request.path == transactions_path %>
      <div class="bg-white shadow-xl h-14 flex items-center justify-between px-4">
        <p class="text-gray-500">Gift credit</p>
        <p class="text-gray-700 font-semibold">$<%= @transactions.sum(:amount) || 0 %></p>
      </div>
    <% end %>
  </div>
  <div class="pt-28">
    <%= render partial: "partials/notices" %>
  </div>
<% end %>


<%# menu popup %>
<div class="fixed z-30 bg-primary-blue inset-0 overflow-y-hidden menu-popup hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="pt-4 px-4 pb-20 text-center">
    <div class="flex justify-end h-auto">
      <button type="button" class="bg-white flex items-center justify-center rounded-md text-primary-blue h-8 w-8 text-center close-menu-icon">
        <span class="sr-only">Close</span>
        <!-- Heroicon name: outline/x -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <% if current_user %>
    <div class="mb-10">
      <div class="flex flex-col py-2 my-3 items-center justify-center text-white">
        <div class="h-28 w-28">
          <% if current_user.profile_pic.attached? %>
            <%= image_tag current_user.profile_pic, alt: "profile-photo", class: "rounded-full h-full w-full" %>
          <% else %>
            <%= image_tag "user-gray.png", class: "rounded-full h-full w-full" %>
          <% end %>
        </div>
        <div class="text-2xl mt-4">
          <p><%= current_user.name %></p>
        </div>
      </div>
    </div>

    
    <ul class="flex flex-col space-y-5 text-gray-300">
      <li class="flex items-center h-auto space-x-5">
        <div class="h-8 w-10 border border-gray-300 rounded-full flex items-center justify-center">
          <%= image_tag "settings-gear.svg", class: "h-5 w-6" %>
        </div>
        <div class="w-full side-nav-links">
          <%= link_to update_user_path(current_user) do %>
            <p class="flex justify-start">Account Settings</p>
            <div class="border-b border-gray-300 mt-3"></div>
          <% end %>
        </div>
      </li>
      <li class="flex items-center h-auto space-x-5">
        <div class="h-8 w-10 border border-gray-300 rounded-full flex items-center justify-center">
          <%= image_tag "add-categories.svg", class: "h-5 w-6" %>
        </div>
        <div class="w-full side-nav-links">
          <%= link_to group_new_path do %>
            <p class="flex justify-start">Add Category</p>
            <div class="border-b border-gray-300 mt-3"></div>
          <% end %>
        </div>
      </li>
      <li class="flex items-center h-auto space-x-5">
        <div class="h-8 w-10 border border-gray-300 rounded-full flex items-center justify-center">
          <%= image_tag "payment-dollar.svg", class: "h-5 w-6" %>
        </div>
        <div class="w-full side-nav-links">
          <%= link_to transactions_new_path do %>
            <p class="flex justify-start">Add Transaction</p>
            <div class="border-b border-gray-300 mt-3"></div>
          <% end %>
        </div>
      </li>
      <li class="flex items-center h-auto space-x-5">
        <div class="h-8 w-10 border border-gray-300 rounded-full flex items-center justify-center">
          <%= image_tag "categories.svg", class: "h-5 w-6" %>
        </div>
        <div class="w-full side-nav-links">
          <%= link_to group_path do %>
            <p class="flex justify-start">View Categories</p>
            <div class="border-b border-gray-300 mt-3"></div>
          <% end %>
        </div>
      </li>
      <li class="flex items-center h-auto space-x-5">
        <div class="h-8 w-10 border border-gray-300 rounded-full flex items-center justify-center">
          <%= image_tag "money-transfer.svg", class: "h-5 w-6" %>
        </div>
        <div class="w-full side-nav-links">
          <%= link_to transactions_path do %>
            <p class="flex justify-start">View Transactions</p>
            <div class="border-b border-gray-300 mt-3"></div>
          <% end %>
        </div>
      </li>
      <li class="flex items-center h-auto space-x-5">
        <div class="h-8 w-10 border border-gray-300 rounded-full flex items-center justify-center">
          <%= image_tag "exit-sign.svg", class: "h-5 w-6" %>
        </div>
        <div class="w-full side-nav-links">
          <%= button_to destroy_user_session_path, method: :delete, class: "flex justify-start" do %>
            <p>Logout</p>
          <% end %>
        </div>
      </li>
    </ul>
    <% end %>
  </div>
</div>

app/views/partials/_showCard.html.erb
<div class="pt-10 pb-36">
  <% if view == "group" %>
    <% data.each do |group| %>
      <div class="py-2 px-3">
        <%= link_to single_group_path(group) do %>
          <div class="bg-white flex items-center rounded h-auto p-2 space-x-3 shadow-md">
            <div class="h-16 w-16">
              <% if group.icon.attached? %>
                <%= image_tag group.icon, alt: "group-photo" %>
              <% end %>
            </div>
            <div class="flex flex-col justify-between h-14 w-full">
              <div class="flex justify-between text-sm">
                <p class="text-gray-500"><%= group.name %></p>
                <p class="text-gray-700 font-semibold right-0">$<%= group.entities.sum(:amount) || 0 %></p>
              </div>
              <div>
                <p class="text-gray-500 text-sm">
                  <%= group.created_at.strftime("%e %b, %Y") %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <% data.each do |transaction| %>
      <div class="py-2 px-3">
        <%= link_to single_group_path(transaction.group_id) do %>
          <div class="bg-white flex items-center rounded h-auto p-2 space-x-3 shadow-md">
            <div class="h-16 w-16">
              <% if transaction.group.icon.attached? %>
                <%= image_tag transaction.group.icon, alt: "group-photo" %>
              <% end %>
            </div>
            <div class="flex flex-col justify-between h-14 w-full">
              <div class="flex justify-between text-sm">
                <p class="text-gray-500"><%= transaction.group.name %></p>
                <p class="text-gray-700 font-semibold right-0">$<%= transaction.amount %></p>
              </div>
              <div>
                <p class="text-gray-500 text-sm">
                  <%= transaction.created_at.strftime("%e %b, %Y at %H:%M") %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/partials/_transactionForm.html.erb
<div class="bg-gray h-screen">
  <%= form_with model: entity_model, url: entity_path do |f| %>

    <div class="">
      <div class="mt-10 text-primary-gray">
        <%= f.text_field :name,
          autofocus: true,
          autocomplete: "name",
          placeholder: "Transaction name",
          class: "appearance-none block w-full px-3 py-2 border border-gray-300 h-14 focus:outline-none focus:ring-primary-blue focus:border-primary-blue" %>

        <%= f.number_field :amount,
          autofocus: true,
          placeholder: "Transaction amount",
          class: "appearance-none block w-full px-3 py-2 border border-gray-300 h-14 focus:outline-none focus:ring-primary-blue focus:border-primary-blue" %>

      
        <% if session[:is_transaction_triggered_from_detail] == nil %>
          <%= f.collection_select :group_id, groups, :id, :name,
            include_blank: 'Select a category',
            class: "appearance-none block w-screen px-3 py-2 border border-gray-300 h-14 focus:outline-none focus:ring-primary-blue focus:border-primary-blue" %>
        <% end %>

        <div class="flex items-center justify-center mt-16">
          <% if entity_path == transactions_new_path %>
            <%= f.submit "SAVE", class: "actions cursor-pointer bg-primary-green p-4 w-48 rounded-md text-white font-semibold text-center" %>
          <% else %>
            <%= f.submit "UPDATE", class: "actions cursor-pointer bg-primary-green p-4 w-48 rounded-md text-white font-semibold text-center" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<div class="flex flex-col mt-10">
  <div class="flex space-x-10 mx-10">
    <%- if controller_name != 'sessions' %>
      <%= link_to "Log in", new_session_path(resource_name),
        class: "actions cursor-pointer bg-gray-400 border p-3 w-1/2 rounded-md text-white font-semibold text-center" %>
    <% end %>

    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <%= link_to "Sign up", new_registration_path(resource_name),
        class: "actions cursor-pointer bg-gray-400 border p-3 w-1/2 rounded-md text-white font-semibold text-center" %>
    <% end %>
  </div>
  <div class="text-center mt-5">
    <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
      <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
    <% end %>
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <% end %>
  </div>
</div>



<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>